
export const categories = [
  'All',
  'Taarak Mehta',
  'Doraemon',
  'React',
  'Music',
  'Live',
  'Gadgets',
  'Programming',
  'Podcasts',
  'Computers',
  'Others',
];

export const videos = [
  {
    id: "1",
    title: "Exploring React Native in 10 Minutes!",
    channelTitle: "CodeWithArpit",
    thumbnail: "https://dummyimage.com/400x225/000/fff&text=Thumbnail+1",
    avatar: "https://dummyimage.com/100x100/000/fff&text=A",
    duration: "10:23",
    publishedText: "2 hours ago",
  },
  {
    id: "2",
    title: "Understanding JavaScript Closures",
    channelTitle: "Dev Insights",
    thumbnail: "https://dummyimage.com/400x225/111/fff&text=Thumbnail+2",
    avatar: "https://dummyimage.com/100x100/111/fff&text=D",
    duration: "8:45",
    publishedText: "1 day ago",
  },
  {
    id: "3",
    title: "Top 5 UI Design Trends for 2025",
    channelTitle: "UI Masters",
    thumbnail: "https://dummyimage.com/400x225/222/fff&text=Thumbnail+3",
    avatar: "https://dummyimage.com/100x100/222/fff&text=U",
    duration: "15:12",
    publishedText: "3 days ago",
  },
  {
    id: "4",
    title: "How to Build an E-commerce App with React Native",
    channelTitle: "Mobile Dev Hub",
    thumbnail: "https://dummyimage.com/400x225/333/fff&text=Thumbnail+4",
    avatar: "https://dummyimage.com/100x100/333/fff&text=M",
    duration: "22:30",
    publishedText: "5 days ago",
  },
  {
    id: "5",
    title: "The Future of AI in Software Development",
    channelTitle: "TechTalks",
    thumbnail: "https://dummyimage.com/400x225/444/fff&text=Thumbnail+5",
    avatar: "https://dummyimage.com/100x100/444/fff&text=T",
    duration: "18:56",
    publishedText: "1 week ago",
  },
  {
    id: "6",
    title: "Mastering Data Structures in DSA",
    channelTitle: "CodeCamp",
    thumbnail: "https://dummyimage.com/400x225/555/fff&text=Thumbnail+6",
    avatar: "https://dummyimage.com/100x100/555/fff&text=C",
    duration: "30:45",
    publishedText: "2 weeks ago",
  },
  {
    id: "7",
    title: "Python for Beginners: Full Course",
    channelTitle: "Programming Guru",
    thumbnail: "https://dummyimage.com/400x225/666/fff&text=Thumbnail+7",
    avatar: "https://dummyimage.com/100x100/666/fff&text=P",
    duration: "2:05:30",
    publishedText: "3 weeks ago",
  },
  {
    id: "8",
    title: "How to Ace Your First Internship Interview",
    channelTitle: "Career Boost",
    thumbnail: "https://dummyimage.com/400x225/777/fff&text=Thumbnail+8",
    avatar: "https://dummyimage.com/100x100/777/fff&text=CB",
    duration: "12:15",
    publishedText: "1 month ago",
  },
  {
    id: "9",
    title: "React vs Vue: Which One Should You Learn?",
    channelTitle: "Frontend Masters",
    thumbnail: "https://dummyimage.com/400x225/888/fff&text=Thumbnail+9",
    avatar: "https://dummyimage.com/100x100/888/fff&text=F",
    duration: "9:30",
    publishedText: "1 month ago",
  },
  {
    id: "10",
    title: "How to Deploy a Full Stack App for Free",
    channelTitle: "DevOps Simplified",
    thumbnail: "https://dummyimage.com/400x225/999/fff&text=Thumbnail+10",
    avatar: "https://dummyimage.com/100x100/999/fff&text=D",
    duration: "14:50",
    publishedText: "2 months ago",
  },
];